### ISSUE TITLE
cdklocal bootstrap fails complaining about StagingBucket

### ISSUE THREAD

**Issue by Tehnix** [localstack/aws-cdk-local#1] opened 2020-10-18 20:24 UTC
## Description

When trying to prepare the LocalStack service for CDK, the `cdklocal bootstrap` seems to fail:

```
$ cdklocal bootstrap
 ⏳  Bootstrapping environment aws://000000000000/eu-central-1...
CDKToolkit: creating CloudFormation changeset...
[··························································] (0/3)

   Environment aws://000000000000/eu-central-1 failed bootstrapping: Error [ValidationError]: Template error: resource StagingBucket does not support attribute type RegionalDomainName in Fn::GetAtt
    at Request.extractError (/home/tehnix/GitHub/codetalkio/patterns-serverless-rust-minimal/node_modules/aws-cdk/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/home/tehnix/GitHub/codetalkio/patterns-serverless-rust-minimal/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/tehnix/GitHub/codetalkio/patterns-serverless-rust-minimal/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/tehnix/GitHub/codetalkio/patterns-serverless-rust-minimal/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/home/tehnix/GitHub/codetalkio/patterns-serverless-rust-minimal/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/tehnix/GitHub/codetalkio/patterns-serverless-rust-minimal/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/tehnix/GitHub/codetalkio/patterns-serverless-rust-minimal/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/tehnix/GitHub/codetalkio/patterns-serverless-rust-minimal/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/tehnix/GitHub/codetalkio/patterns-serverless-rust-minimal/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/home/tehnix/GitHub/codetalkio/patterns-serverless-rust-minimal/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'ValidationError',
  time: 2020-10-18T20:14:26.279Z,
  requestId: undefined,
  statusCode: 400,
  retryable: false,
  retryDelay: 953.511101390292
}
Template error: resource StagingBucket does not support attribute type RegionalDomainName in Fn::GetAtt
```

Not really sure where to dig for more information at the moment. For reference I'm running it against a a dockerized LocalStack ([using the standard [docker-compose.yml](https://github.com/codetalkio/patterns-serverless-rust-minimal/blob/94a376dbe052e302f5583099f2761a7c6c025034/docker-compose.yml) setup).

- cdklocal version 1.65.0
- cdk version 1.65.0 (tested with 1.68.0 also)

**Comment by whummer** [comment] 2020-10-19 22:46
Thanks for reporting @Tehnix . Not sure if the validation error (`ValidationError`) is related to LocalStack - does this CDK script work against real AWS? Any chance you can share a minimal snippet of your CDK program here, to help us reproduce this issue? Thanks!

**Comment by 10xjs** [comment] 2020-10-20 01:33
@whummer This bug bothered me enough to dig into the `moto` source. I have a proposed fix for this here: https://github.com/spulec/moto/pull/3396.

**Comment by whummer** [comment] 2020-10-21 20:51
Great, thanks for creating the upstream PR @10xjs - looks like there's still a minor build/lint error, can we try to fix it? Once it is merged, we can integrate the latest moto version into LocalStack. Thanks for your help!

**Comment by skyrpex** [comment] 2020-10-28 19:02
The PR got merged to moto, am I right? Is there something I can do to speed this process?

**Comment by whummer** [comment] 2020-10-29 08:30
@Tehnix @skyrpex @10xjs Thanks for the update - the latest moto changes are now available in LocalStack. Can you please do a `docker pull localstack/localstack` and give it another try with the latest version? Thanks

**Comment by Tehnix** [comment] 2020-10-29 08:56
@whummer just tried, both with `docker pull localstack/localstack` and by completely removing any existing localstack image to be sure.

I still get the error, but at least LocalStack seems to be outputting something now :) 

```
...
localstack_main | Starting mock SQS service on http port 4566 ...
localstack_main | Starting mock SSM service on http port 4566 ...
localstack_main | Waiting for all LocalStack services to be ready
localstack_main | Ready.
localstack_main | 2020-10-29T08:53:42:INFO:localstack.utils.analytics.profiler: Execution of "start_api_services" took 9612.378120422363ms
localstack_main | 2020-10-29T08:53:59:WARNING:localstack.services.cloudformation.cloudformation_starter: Unable to determine physical_resource_id for resource <class 'localstack.services.cloudformation.service_models.S3BucketPolicy'>
```

For references, the services I'm running are `serverless,cloudformation,iam,sts,sqs,ssm,s3,cloudwatch,cloudwatch-logs,lambda,dynamodb,apigateway`.

**Comment by whummer** [comment] 2020-10-29 11:11
Thanks @Tehnix , can you please try pulling again - looks like the CI pipeline had some issues creating the latest image.

If it still doesn't work, can you please share the full error and container logs, as well as the image tag/age:
```
docker images | grep localstack/localstack
```
Thanks

**Comment by Tehnix** [comment] 2020-10-29 11:25
@whummer awesome, that works :)

**Closed** 2020-10-29 11:39 UTC
Labels: bug, needs-triaging
