### ISSUE TITLE
LOC-20 ⁃ Internal error when bootstraping

### ISSUE THREAD

**Issue by BlueMagma2** [localstack/aws-cdk-local#6] opened 2020-11-11 11:49 UTC
```
$ cdklocal --version
1.72.0 (build c2f38e8)

$ localstack --version
0.12.2

$ cat ~/.aws/credentials
[local]
aws_access_key_id = dummy
aws_secret_access_key = dummy

$ echo $AWS_PROFILE
local
```

I start localstack like this:

```
$ SERVICES=serverless,sqs,sns DEFAULT_REGION=eu-west-2 DEBUG=1 localstack start
```

I run:

```
$ cdklocal bootstrap -c env=local aws://000000000000/eu-west-2
```

The logs from localstack are the followings:

```
2020-11-11T11:48:16:DEBUG:localstack.services.cloudformation.cloudformation_listener: Error response for CloudFormation action "DescribeStacks" (400) POST /: b'<ErrorResponse xmlns="http://cloudformation.amazonaws.com/doc/2010-05-15/">\n  <Error>\n    <Type>Sender</Type>\n    <Code>ValidationError</Code>\n    <Message>Stack with id CDKToolkit does not exist</Message>\n  </Error>\n  <RequestId>cf4c737e-5ae2-11e4-a7c9-ad44eEXAMPLE</RequestId>\n</ErrorResponse>'
2020-11-11T11:48:16:DEBUG:localstack.services.cloudformation.cloudformation_listener: Error response for CloudFormation action "DescribeStacks" (400) POST /: b'<ErrorResponse xmlns="http://cloudformation.amazonaws.com/doc/2010-05-15/">\n  <Error>\n    <Type>Sender</Type>\n    <Code>ValidationError</Code>\n    <Message>Stack with id CDKToolkit does not exist</Message>\n  </Error>\n  <RequestId>cf4c737e-5ae2-11e4-a7c9-ad44eEXAMPLE</RequestId>\n</ErrorResponse>'
2020-11-11T11:48:16:DEBUG:localstack.services.cloudformation.cloudformation_listener: Error response for CloudFormation action "CreateChangeSet" (500) POST /: b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n'
2020-11-11 11:48:16,640:API: Error on request:
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/server.py", line 168, in __call__
    return backend_app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/utils.py", line 151, in __call__
    result = self.callback(request, request.url, {})
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/responses.py", line 202, in dispatch
    return cls()._dispatch(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/responses.py", line 312, in _dispatch
    return self.call_action()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/responses.py", line 397, in call_action
    response = method()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/utils.py", line 282, in _wrapper
    response = f(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/cloudformation/responses.py", line 135, in create_change_set
    parameters = {
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/cloudformation/responses.py", line 136, in <dictcomp>
    param["parameter_key"]: param["parameter_value"]
KeyError: 'parameter_value'
2020-11-11T11:48:17:DEBUG:localstack.services.cloudformation.cloudformation_listener: Error response for CloudFormation action "CreateChangeSet" (500) POST /: b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n'

```

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-20) by [Unito](https://www.unito.io/learn-more)

**Comment by miho120** [comment] 2020-11-12 17:05
Hi @BlueMagma2 
I'm not able to reproduce your issue 😔 I tried different python versions, localstack from repo and PyPI, different versions of aws-cdk.

All of my tries were successful and I saw this message every time without issue you've provided:
```
$ cdklocal bootstrap -c env=local aws://000000000000/eu-west-2                                                                                         
 ⏳  Bootstrapping environment aws://000000000000/eu-west-2...
CDKToolkit: creating CloudFormation changeset...
[··························································] (0/3)

 ✅  Environment aws://000000000000/eu-west-2 bootstrapped.
```

Could you share a little bit more information like `pip freeze`, exact python version and OS you're using?
You can also try what I did:
```bash
$ python3.8 -m venv local38
$ source local38/bin/activate
$ pip install localstack
$ SERVICES=serverless,sqs,sns DEFAULT_REGION=eu-west-2 DEBUG=1 localstack start
```
```bash
$ npm install -g aws-cdk-local
$ cdklocal bootstrap -c env=local aws://000000000000/eu-west-2
```

Let me know if this works.

**Comment by jackmcguire1** [comment] 2020-11-27 11:18
still getting this error :(

`Environment aws://000000000000/eu-west-2 failed bootstrapping: Error [ValidationError]: Template error: resource StagingBucket does not support attribute type RegionalDomainName in Fn::GetAtt
    at Request.extractError (/usr/local/lib/node_modules/aws-cdk-local/node_modules/aws-cdk/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/usr/local/lib/node_modules/aws-cdk-local/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/aws-cdk-local/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/aws-cdk-local/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/usr/local/lib/node_modules/aws-cdk-local/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/aws-cdk-local/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/aws-cdk-local/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/aws-cdk-local/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/aws-cdk-local/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/usr/local/lib/node_modules/aws-cdk-local/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'ValidationError',
  time: 2020-11-27T11:17:23.816Z,
  requestId: undefined,
  statusCode: 400,
  retryable: false,
  retryDelay: 118.19719354596891
}
Template error: resource StagingBucket does not support attribute type RegionalDomainName in Fn::GetAtt`

**Comment by apalumbo** [comment] 2020-12-08 11:45
@jackmcguire1 you should pull the new image of localstack, the error was fixed on moto and the image has been updated

docker images | grep localstack/localstack
check the ageing of you image and pull the new one

**Comment by whummer** [comment] 2020-12-08 12:02
Great, thanks for confirming the fix @apalumbo . Please report here (with a small sample and detailed steps to reproduce) if the problem persists with the `latest` Docker image @jackmcguire1 . Thanks!

**Closed by whummer** 2020-12-08 12:02 UTC
